development:
  dialect: postgres
  datasource: host=${DEV_DATABASE_HOST} user=postgres password=postgres dbname=foo sslmode=disable
  dir: db
  table: schema_migrations
circleci:
  dialect: postgres
  datasource: host=localhost user=postgres password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
  dir: db
  table: schema_migrations
