development:
  dialect: postgres
  # datasource: host=localhost user=postgres password=postgres dbname=haskell sslmode=disable
  datasource: host=localhost user=postgres password=postgres dbname=example sslmode=disable
  dir: db
  table: schema_migrations
circleci:
  dialect: postgres
  datasource: host=localhost user=postgres password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
  dir: db
  table: schema_migrations
