name: sql-example
version: 0.1.0.0
github: pyar6329/sql-examples
license: MIT
author: 'Tsukasa Arima'
maintainer: pyar6329@gmail.com
copyright: '2019 Tsukasa Arima'
category: Web
description: 'Please see the README on GitHub at <https://github.com/pyar6329/sql-examples/tree/master/src/haskell#readme>'

extra-source-files:
  - README.md
  - package.yaml

dependencies:
  - 'base >= 4.7 && < 5'
  - dhall
  - esqueleto
  - lens
  - monad-control
  - monad-logger
  - mtl
  - persistent
  - persistent-postgresql
  - persistent-template
  - text
  - time

library:
  source-dirs: src

executables:
  sql-example-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - sql-example

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - sql-example
      - hspec
