name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ['8.6.4']
        cabal: ['3.0']
        cache-version: ["v4"]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Cache .stack/pantry
      id: cache-pantry
      uses: actions/cache@v1
      with:
        path: ~/.stack-temp/pantry
        key: ${{ runner.os }}-pantry-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-pantry-

    - name: Move .stack/pantry to temp
      uses: matsubara0507/actions/move-files@master
      with:
        source_dir: ~/.stack-temp/pantry
        source_files: |
          pantry
        target_dir: ~/.stack

    - name: install dependent packages
      run: |
        sudo apt-get install -y libpq-dev
    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - uses: mstksg/setup-stack@v1
    - name: Debug cache
      run: |
        du -sh ~/.stack
        du -sh ~/.stack*
        ls -la ~/.stack/
    - name: Install dependencies
      run: |
        cd src/haskell
        stack --system-ghc build --test --no-run-tests --only-dependencies --fast -j0 --ghc-options "-dynamic +RTS -A128m -RTS"
    # - name: Run tests
    #   run: |
    #     cd src/haskell
    #     stack --system-ghc test --fast -j0 --ghc-options "-dynamic +RTS -A128m -RTS"
    # - name: Build binary
    #   run: |
    #     cd src/haskell
    #     stack --system-ghc install --local-bin-path=./bin
    #
