name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ['8.6.4']
        cabal: ['3.0']
        cache-version: ["v4"]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Cache .stack/pantry
      id: cache-pantry
      uses: actions/cache@v1
      with:
        path: ~/.tmp
        key: ${{ runner.os }}-pantry-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-pantry-

    - name: Restore from ~/.tmp/pantry to ~/.stack/pantry
      run: |
        if [ -e ~/.tmp/pantry ]; then
          mv ~/.tmp/pantry ~/.stack/pantry
        fi
        if [ -e ~/.tmp/bin ]; then
          mv ~/.tmp/bin/* /usr/local/bin
        fi

    - name: install dependent packages
      run: |
        sudo apt-get install -y libpq-dev

    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: setup stack
      run: |
        if [ ! -e /usr/local/bin/stack ]; then
          curl -sL https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C /usr/local/bin */stack
        fi
        stack update

    - name: Install dependencies
      run: |
        cd src/haskell
        stack --system-ghc build --test --no-run-tests --only-dependencies --fast -j0 --ghc-options "-dynamic +RTS -A128m -RTS"

    - name: Save cache ~/.stack/pantry to ~/.tmp/pantry
      run: |
        mv ~/.stack/pantry ~/.tmp/pantry

    - name: Save cache ~/.local/bin/stack to ~/.tmp/bin
      run: |
        if [ ! -e ~/.tmp/bin ]; then
          mkdir -p ~/.tmp/bin
        fi
        mv /usr/local/bin/stack ~/.tmp/bin/stack
 
    # - name: Run tests
    #   run: |
    #     cd src/haskell
    #     stack --system-ghc test --fast -j0 --ghc-options "-dynamic +RTS -A128m -RTS"
    # - name: Build binary
    #   run: |
    #     cd src/haskell
    #     stack --system-ghc install --local-bin-path=./bin
    #
